Apple homepage
shadymedy/apple-old-version-website pull request #1
Opened 2019-08-30 19:01 UTC by shadymedy

2019-08-30 21:06 UTC, samgaco requested changes
#### Hi :hand: 

#### Everything is looking perfect! just one requirement before proceeding:

- [ ]  [REQUIERED] The four boxes in **bottom-footer** should be linked


- [ ]  [OPTIONAL] There is a horizontal scrolling bar showing when seeing it from my browser. Maybe you could work on the units you are using to try to get the website adaptative to every screen.


#### Work on this and submit back for review once you are done. Regards! :muscle:

2019-08-30 21:06 UTC, samgaco commented on index.html
> +    </div>
This four boxes should be linked ( `<a>` )

2019-08-31 22:17 UTC, Oghenebrume50 commented
Reviewing.....

2019-08-31 22:28 UTC, Oghenebrume50 requested changes
Hi @shadymedy good job on this one, but there is just one change to be made, the horizontal bar still shows, please try to fix it with the comments I have made so far when done request a re-review. :wink:

2019-08-31 22:28 UTC, Oghenebrume50 commented on css/styles.css
> +  width: 1440px;
You do not need to set an explicit width like this, if you use more responsive units on your containers this would not be needed,

2019-08-31 22:28 UTC, Oghenebrume50 commented on css/styles.css
> +  width: 356px;
Use more responsive units here, like em, rem or percentage, if you do this and remove the width on the body, the horizontal bar should go off

2019-09-02 19:06 UTC, samgaco commented
#### Hi @shadymedy :hand: 

#### Your project is approved :heavy_check_mark:  congratulations on that :clap: 

* **[OPTIONAL]**  _Try to fix the horizontal scrolling bar issues without using overflow moving forward. (Right now the four boxes at the bottom don't look compensated, you can tell one of them is crossing the right margin anyways)_

##### You may now merge to the master branch and submit the project completion form :+1:

2019-09-03 09:52 UTC, merged